import type { Metadata } from 'next'
import './globals.css'
import { Murecho } from 'next/font/google'
import ReactQueryProvider from '@/components/providers/ReactQueryProvider'
import { Toaster } from 'sonner'

const murecho = Murecho({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${murecho.className} antialiased`}>
        <ReactQueryProvider>
          {children}
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  )
}
